name: Update Repo Packages

on:
  push:
    paths:
      - 'debs/**/*.deb'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2 xz-utils

      - name: Generate Packages
        run: |
          dpkg-scanpackages -m ./debs > Packages
          bzip2 -c9 Packages > Packages.bz2
          xz -c9 Packages > Packages.xz
          xz -5fkev --format=lzma Packages > Packages.lzma

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Packages Packages.bz2 Packages.xz Packages.lzma
          git commit -m "Auto-update Packages" || echo "No changes to commit"
          git push
